### ISSUE TITLE
.installed parse error

### ISSUE THREAD

**Issue by thet** [buildout/buildout#239] opened 2015-02-18 21:28 UTC
after running buildout the second time, i often get parse errors with the ``.installed`` file.
traceback:

```
While:
  Installing.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/thet-data/dotfiles-thet/home/.buildout/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 1942, in main
    getattr(buildout, command)(args)
  File "/home/thet-data/dotfiles-thet/home/.buildout/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 475, in install
    )= self._read_installed_part_options()
  File "/home/thet-data/dotfiles-thet/home/.buildout/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 773, in _read_installed_part_options
    sections = zc.buildout.configparser.parse(fp, old)
  File "/home/thet-data/dotfiles-thet/home/.buildout/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/configparser.py", line 234, in parse
    raise e
ParsingError: File contains parsing errors: /home/thet-data/data/dev/amkumma/amkumma-buildout/.installed.cfg
	[line 144]: 'eggs + = ak.policy\n'
```

and this is the section in the ``.installed`` file:

```
[test]
__buildout_installed__ = /home/thet-data/data/dev/amkumma/amkumma-buildout/parts/test
	/home/thet-data/data/dev/amkumma/amkumma-buildout/bin/test
__buildout_signature__ = zc.recipe.testrunner-1.2.1-py2.7.egg zc.recipe.egg-1.3.2-py2.7.egg setuptools-2.2-py2.7.egg zope.testing-3.9.7-py2.7.egg zc.buildout-2.2.1-py2.7.egg zope.interface-3.6.7-py2.7-linux-x86_64.egg zope.exceptions-3.6.2-py2.7.egg
_b = /home/thet-data/data/dev/amkumma/amkumma-buildout/bin
_d = /home/thet-data/data/dev/amkumma/amkumma-buildout/develop-eggs
_e = /home/thet/.buildout/eggs
bin-directory = /home/thet-data/data/dev/amkumma/amkumma-buildout/bin
defaults = ['--auto-color', '--auto-progress', '--ignore_dir=bower_components', '--ignore_dir=node_modules']
develop-eggs-directory = /home/thet-data/data/dev/amkumma/amkumma-buildout/develop-eggs
eggs = collective.explicitacquisition [test]
eggs + = ak.policy
	Pillow
	plone.app.debugtoolbar
	plone.reload
	z3c.checkversions
	z3c.dependencychecker
	Products.PrintingMailHost
	collective.z3cinspector
	ipdb
	vimpdb
	collective.jsonify
eggs-directory = /home/thet/.buildout/eggs
environment = environment
executable = /home/thet/dev/python27/bin/python
find-links = http://effbot.org/downloads/
	file:///home/thet-data/data/dev/amkumma/amkumma-buildout/dist-eggs/
location = /home/thet-data/data/dev/amkumma/amkumma-buildout/parts/test
python = buildout
recipe = zc.recipe.testrunner
script = /home/thet-data/data/dev/amkumma/amkumma-buildout/bin/test
```

line 144 refers to this one:
```eggs + = ak.policy```

**Comment by tseaver** [comment] 2015-02-18 21:46
Duplicate of #63.

**Closed by tseaver** 2015-02-18 21:46 UTC
Labels: duplicate
