### ISSUE TITLE
Tests cannot run on Python 3.9

### ISSUE THREAD

**Issue by icemac** [buildout/buildout#499] opened 2020-02-11 15:21 UTC
`tox.ini` uses `dev.py` which uses `ez_setup.py` which installs `setuptools==33.1.1`.
This `setuptools` version uses `collections.MutableMapping` which no longer exists in Python 3.9.

It seems we have to rethink how we run the tests for `buildout` 😞

**Comment by idgserpro** [comment] 2020-03-06 00:09
@icemac maybe need to use a Python with `setuptools` installed, instead of using an egg installed with `ez_setup.py`. `ez_setup.py` is deprecated.

**Comment by gotcha** [comment] 2020-03-06 14:35
@idgserpro There are buildout tests that demand to run in a Python environment without setuptools installed. But we might get there by using a `virtualenv`, installing `zc.buildout` then uninstalling `setuptools` before running the tests.

**Comment by idgserpro** [comment] 2020-03-07 02:28
@gotcha I thought just that. But I don't think `virtualenv` is necessary. The `buildout` tests compiles your own Pythons. Python 3 comes with `setuptools` already installed. We just need to remove the [without-ensurepip](https://github.com/buildout/buildout/blob/a2a3dd72611c7e04e4d205f96dacdef2c1657902/Makefile#L19) argument at the time of compilation. For Python 2, we can use `get-pip.py`, which also installs `setuptools`. If I have time, I can try a PR.

**Comment by idgserpro** [comment] 2020-03-09 13:02
@gotcha  it won't be that simple. The idea didn't work. It seems that the restart of the buildout only occurs if the `setuptools` is an egg, outside the site-packages. Using `setuptools` from site-packages, the buildout restart does not occur, and then a `setuptools` egg's isn't used. Therefore, we cannot uninstall `setuptools` from site-packages. I think it will be necessary to change the tests so that Python is not needed without `setuptools` on site-packages. Perhaps the restart functionality should be removed. In the Plone world, we already installed `setuptools` with `pip`, before running the buildout.

As `easy_install` is also deprecated, I have my doubts whether `setuptools` will continue to download and install other packages. Maybe @jaraco can give some clarification.

**Comment by jaraco** [comment] 2020-03-09 21:56
That's right - setuptools is trying to get out of the business of downloading or installing packages. If you can find a solution for those use-cases that relies instead on pip, you'll be happier for longer.

> ... Change the tests so that Python is not needed without `setuptools` on site-packages. Perhaps the restart functionality should be removed.

I don't understand what these tests are or what the restart functionality is. Why does restart functionality exist?

What is the target environment you're trying to create? Perhaps I could demonstrate a way to help.

**Comment by reinout** [comment] 2020-03-09 22:01
The restart functionality is for updating. Some version of setuptools and buildout is installed, then buildout is run, reads its config file and discovers a newer version of setuptools or buildout is needed. It grabs it and restarts. (At least, that's been my understanding).

Pip: the continuing problem is that pip doesn't have an API and doesn't want to have it. Unless something changed. So if you want to use it, you're "reduced" to calling it on the command line :-)

**Comment by reinout** [comment] 2020-03-09 22:03
As it is (or is becoming) standard practice to pip-install setuptools and buildout and *then* run buildout: it could be a good idea to remove part of the bootstrapping.

**Comment by idgserpro** [comment] 2020-03-10 01:10
> What is the target environment you're trying to create?

@jaraco we are trying to create the "initial environment" for the tests, without using `ez_setup.py`, since, as the issue description says, it doesn't work for Python 3.9 (and probably for new versions of `setuptools`).  It's basically doing the [make build](https://github.com/buildout/buildout/blob/a2a3dd72611c7e04e4d205f96dacdef2c1657902/Makefile#L47-L48). 

The dev.py script is executed with Python without `setuptools`. `setuptools` is [installed with ez_setup.py](https://github.com/buildout/buildout/blob/e4101a23526412ef59a11b9e3f8bce5f3e0b5b0e/dev.py#L50-L51), and an egg is generated. The idea was to run dev.py with a Python with `setuptools` installed on site-packages, so that you don't need to use ez_setup.py, and then uninstall `setuptools`, since some tests want a Python without `setuptools`. I expected that when executing the buildout, the restart would occur and a egg be generate. Thus, it would be possible to uninstall `setuptools` from site-packages. But the restart doesn't occur in this situation, and it is not possible to uninstall setuotools. So, I think we will have to change the tests that expect a Python without `setuptools`.

**Comment by jaraco** [comment] 2020-03-11 02:20
Does [pip-run](https://pypi.org/project/pip-run) (tentatively slated for inclusion in pip) provide any inspiration for bootstrapping? In conjunction with the [runpy-invoke branch](/jaraco/buildout/tree/runpy-invoke), it becomes trivially easy to get a working bootstrap command running:

```
draft $ pip freeze --all | grep setuptools
draft $ pip-run --use-pep517 git+https://github.com/jaraco/buildout@runpy-invoke -- -m zc.buildout --help
  Running command git clone -q https://github.com/jaraco/buildout /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-o1usinky
Collecting git+https://github.com/jaraco/buildout@runpy-invoke
  Cloning https://github.com/jaraco/buildout (to revision runpy-invoke) to /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-o1usinky
  Running command git checkout -b runpy-invoke --track origin/runpy-invoke
  Switched to a new branch 'runpy-invoke'
  Branch 'runpy-invoke' set up to track remote branch 'runpy-invoke' from 'origin'.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting setuptools>=8.0
  Using cached setuptools-46.0.0-py3-none-any.whl (582 kB)
Building wheels for collected packages: zc.buildout
  Building wheel for zc.buildout (PEP 517) ... done
  Created wheel for zc.buildout: filename=zc.buildout-2.13.4.dev0-py2.py3-none-any.whl size=154160 sha256=b29f17278efdc86ecb60e6b11538ff7634f400d02a46a2288006500212ec3013
  Stored in directory: /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-ephem-wheel-cache-3iwvteza/wheels/0d/f4/2a/5676525107334d9c000bf303d51abe87e908f3bb0a6a8a456b
Successfully built zc.buildout
Installing collected packages: setuptools, zc.buildout
Successfully installed setuptools-46.0.0 zc.buildout-2.13.4.dev0
Usage: buildout [options] [assignments] [command [command arguments]]

Options:

  -c config_file

    Specify the path to the buildout configuration file to be used.
    This defaults to the file named "buildout.cfg" in the current
    working directory.

  -D

    Debug errors.  If an error occurs, then the post-mortem debugger
    will be started. This is especially useful for debuging recipe
    problems.

  -h, --help

    Print this message and exit.

  -N

    Run in non-newest mode.  This is equivalent to the assignment
    buildout:newest=false.  With this setting, buildout will not seek
    new distributions if installed distributions satisfy it's
    requirements.

  -q

    Decrease the level of verbosity.  This option can be used multiple times.

  -t socket_timeout

    Specify the socket timeout in seconds.

  -U

    Don't read user defaults.

  -v

    Increase the level of verbosity.  This option can be used multiple times.

  --version

    Print buildout version number and exit.

Assignments are of the form: section:option=value and are used to
provide configuration options that override those given in the
configuration file.  For example, to run the buildout in offline mode,
use buildout:offline=true.

Options and assignments can be interspersed.

Commands:

  install

    Install the parts specified in the buildout configuration.  This is
    the default command if no command is specified.

  bootstrap

    Create a new buildout in the current working directory, copying
    the buildout and setuptools eggs and, creating a basic directory
    structure and a buildout-local buildout script.

  init [requirements]

    Initialize a buildout, creating a minimal buildout.cfg file if it doesn't
    exist and then performing the same actions as for the bootstrap
    command.

    If requirements are supplied, then the generated configuration
    will include an interpreter script that requires them.  This
    provides an easy way to quickly set up a buildout to experiment
    with some packages.

  setup script [setup command and options]

    Run a given setup script arranging that setuptools is in the
    script's path and and that it has been imported so that
    setuptools-provided commands (like bdist_egg) can be used even if
    the setup script doesn't import setuptools.

    The script can be given either as a script path or a path to a
    directory containing a setup.py script.

  annotate

    Display annotated sections. All sections are displayed, sorted
    alphabetically. For each section, all key-value pairs are displayed,
    sorted alphabetically, along with the origin of the value (file name or
    COMPUTED_VALUE, DEFAULT_VALUE, COMMAND_LINE_VALUE).

  query section:key

    Display value of given section key pair.
```

Presumably that invocation of buildout could install whatever versions of buildout or setuptools or whatever are necessary.

What I did find was that with setuptools installed (even as transiently as pip-run does it), buildout doesn't install its egg (it's satisfied by the version that's present), so maybe buildout is still too reliant on conventions made by `easy_install` and `pkg_resources` for this approach to be straightforward.

Thinking of another approach, does the [pip-run project](/jaraco/pip-run) provide any inspiration about invoking pip in a subprocess? I've found the approach to be mostly reliable, even if it doesn't provide a proper procedure call API.

If none of that helps, you're welcome to fork and host the `ez_setup.py` script anywhere you like. In fact, if you want to take over maintenance of it, it could be hosted here in buildout and the scripts that update bootstrap.pypa.io could pull it from here instead of where it used to pull it (pypa/setuptools).

I have some other ideas, but I'll post these for now as I'm not sure when I'll get to the next ideas.

**Comment by idgserpro** [comment] 2020-03-13 04:44
@jaraco `pip-run` cannot be used for bootstrapping of buildout. The buildout generates a script that uses the `zc.buildout` package path. This path must exist after bootstrap. I run:
```
$ pip-run --use-pep517 git+https://github.com/jaraco/buildout@runpy-invoke -- -m zc.buildout init
$ cat bin/buildout #!/tmp/buildout/bin/python

import sys
sys.path[0:0] = [
  '/tmp/pip-run-SZj0bs',
  ]

import zc.buildout.buildout

if __name__ == '__main__':
    sys.exit(zc.buildout.buildout.main())

```
The `/tmp/pip-run-SZj0bs` path doesn't exist after running the `pip-run`. We need to keep virtualenv alive after the bootstrap. We usually bootstrap like this:

```
$ cd folder-of-project
$ virtualenv .
$ ./bin/pip install -r requirements.txt
$ ./bin/buildout
```
requirements.txt:

```
setuptools==40.8.0
zc.buildout==2.13.1
```
buildout.cfg must have the same versions:
```
...
[versions]
setuptools=40.8.0
zc.buildou==2.13.1
```
Commands can be automated with the [plonecli](https://github.com/plone/plonecli#build-your-package)

With that, we are free from `ez_setup.py`. The problem is only the tests of buildout, but it can also be solved, using a Python with setuptools in the site-package. The problem is that it breaks several tests.

Since the upgrade of setuptools only works if the initial setuptools is an egg installed with ez_setup.py, I am proposing to remove this feature.

**Comment by gotcha** [comment] 2020-05-17 13:14
Tests in 3.9 do run. #506 has been merged.

**Closed by gotcha** 2020-05-17 13:14 UTC

**Comment by idgserpro** [comment] 2020-05-20 02:47
> There are buildout tests that demand to run in a Python environment without setuptools installed.

@gotcha what happened to these tests?

**Comment by gotcha** [comment] 2020-05-20 09:29
@idgserpro The statement hereabove should have been: the test suite demands to run in a Python environment without setuptools.

Which is not the case anymore in master. I am not sure I understand why it was needed before. Maybe to test `bootstrap-buildout.py`... which is gone now.

**Comment by mgedmin** [comment] 2020-05-20 09:45
AFAIR Jim Fulton always distrusted distro-packaged Pythons because they did things like split off parts of the stdlib into a separate package (python-profiler), not installed by default and such.  He was a proponent of always building your own Python from upstream sources for production use.  (In fact the first prototype of buildout, before it was zc.buildout, built a Python for you, always, unconditionally.  I always hated discovering that I didn't have zlib-dev or libreadline-dev installed when that happened.  Anyway.)

So the requirement was that buildout had to be able to bootstrap itself and work in a clean upstream Python installation without any extra packages such as setuptools. The test suite was intended to enforce that requirement.

**Comment by gotcha** [comment] 2020-05-20 09:54
FTR, current master still provides a way to run tests against Python built from source.

CI runs tests both against Python from source (in CentOS and Debian containers, in Travis and GitHub) and against GitHub provided Python setups.
