### ISSUE TITLE
Scripts contains path to system directory "dist-packages"

### ISSUE THREAD

**Issue by Cykooz** [buildout/buildout#384] opened 2017-04-24 16:44 UTC
If ``buildout`` is used with ``setuptools > 33.1.1`` then scripts, generated by something like ``zc.recipe.egg``, contains path to system directory ``dist-packages``.

Example:

buildout.cfg
```
[buildout]
parts = script

[script]
recipe = zc.recipe.egg:scripts
eggs = pygments
```

./bin/pygmentize
```
#!/usr/bin/python

import sys
sys.path[0:0] = [
  '/usr/lib/python2.7/dist-packages',
  ]

import pygments.cmdline

if __name__ == '__main__':
    sys.exit(pygments.cmdline.main())
```

Scripts for some packages does not contains this "bug". For example ``celery``:

./bin/celery
```
#!/usr/bin/python

import sys
sys.path[0:0] = [
  '...eggs/celery-4.0.2-py2.7.egg',
  '...eggs/kombu-4.0.2-py2.7.egg',
  '...eggs/billiard-3.5.0.2-py2.7-linux-x86_64.egg',
  '...eggs/pytz-2017.2-py2.7.egg',
  '...eggs/amqp-2.1.4-py2.7.egg',
  '...eggs/vine-1.1.3-py2.7.egg',
  ]

import celery.__main__

if __name__ == '__main__':
    sys.exit(celery.__main__.main())
```

**Comment by leorochael** [comment] 2017-04-24 20:59
I think this is is not a bug.

Buildout doesn't provide isolation from the environment where you're running (you need [virtualenv](https://virtualenv.pypa.io/en/stable/) or [venv](https://docs.python.org/3/library/venv.html) for that).

If there is a version of `pygments` in your environment that setuptools judged as sufficient, then the buildout will use it and the scripts will include a path to it.

You could argue that it's a bug to include a path in the script header to something that would already be on `sys.path` anyway, but that's a much less serious issue.

**Comment by Cykooz** [comment] 2017-04-24 21:49
This behavior only occurs when using ``setuptools > 33.1.1``. Previously, this was not. Now it's breaking all my projects because this path is added somewhere in the middle of the list of other paths.
Why do need to explicitly add this path to the script if the ``buildout`` does not provide isolation? Python will find this folder without explicit instructions in the script.

**Comment by jimfulton** [comment] 2017-04-25 17:17
Setuptools 34 added several new dependencies. If any of these are coming from the Python installation you're using then the directory containing them will be included in the path.

**Comment by Cykooz** [comment] 2017-04-25 17:54
So, in this case I will use setuptools 33.1.1. I'm tired of dealing with new problems every time after the setuptools update.

**Comment by gotcha** [comment] 2017-04-26 15:00
@Cykooz ``bootstrap.py`` accepts a ``--setuptools-version`` argument to pin ``setuptools``

**Comment by Cykooz** [comment] 2017-04-26 15:30
Why ``setuptools`` (called from buildout) looks into the system packages during installation of eggs in to the buildout ``eggs-directory``? Maybe there is a some options in ``setuptools`` for disabling this behavior?

**Comment by jimfulton** [comment] 2017-04-26 16:43
It seems like this (isolation) should be easy, but it's not.  This is partly because system packagers are so innovative about where system packages go, it's hard to distinguish between directories containing system packages and directories containing add-ons.  Python doesn't really provide much help here.  This is why virtualenv is so (damn) heavy handed.

Buildout 1 tried to implement isolation and it got so complicated that buildout became unmaintainable. It's a shame, really.

**Comment by Cykooz** [comment] 2017-04-26 16:49
I dont need full isolation. I only need that the packages installed by the buildout have priority over the system packages.

**Comment by jimfulton** [comment] 2017-04-26 16:50
Honestly, if you have access to a compiler, the solution is actually very easy.  Just build Python from source and omit pip and setuptools from the install.  This is what I've always done and it's really easy.  Most people think this is too painful and instead waste lots of time fighting their system Python.

Almost as good is is creating a pipless virtualenv and using that to run the buildout bootstrap script.  Sadly, there have been problems with the bootstrap script, mainly due to changes in setuptools, over time, but bootstrapping with a clean Python or virtualenv has been the most robust option for me. 

The buildout dev team has a love/hate relationship with the bootstrap script.  Sometimes, I winder if we can't just make a more reliable one that doesn't depend on setuptools so much.

**Comment by jimfulton** [comment] 2017-04-26 16:53
But the problem is that without knowing where the system packages are it's hard to order them properly, and system packagers make this hard.  

The traditional Python install model, you know, the one from 20 years ago, makes this hard too, because it wants to mix files from different packages together, like the packages are being shared on a mainframe or some such.

**Comment by Cykooz** [comment] 2017-04-26 17:01
All paths outside the ``eggs-directory`` can be located at the end of the list of paths. I think this is a fairly simple solution. Isn't it?

**Comment by jimfulton** [comment] 2017-04-26 17:30
I predict there will be some gotcha, however, I think it's worth trying. It couldn't hurt. :)  There's a similar issue with develop eggs, which I think should be put first.

**Closed** 2019-03-05 11:14 UTC
