### ISSUE TITLE
buildout 3: python3.8 install compiles scipy 1.7.3 but whl

### ISSUE THREAD

**Issue by delijati** [buildout/buildout#603] opened 2022-03-07 10:29 UTC
Buildout tries to compile a package even if there is a whl (Python 3.8.12).

```
deps:
❯ env/bin/pip install -U pip setuptools zc.buildout==3.0.0rc2
Successfully installed pip-22.0.4 setuptools-60.9.3 zc.buildout-3.0.0rc2

with pip:
❯ env/bin/pip install scipy==1.7.3 
Collecting scipy==1.7.3
  Using cached scipy-1.7.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.3 MB)
Collecting numpy<1.23.0,>=1.16.5
  Downloading numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     |████████████████████████████████| 16.8 MB 3.0 MB/s             
Installing collected packages: numpy, scipy
Successfully installed numpy-1.22.2 scipy-1.7.3

with buildout:
...
Getting distribution for 'scipy==1.7.3'.
Download cache has scipy 1.7.3 at: /home/xx/.buildout/download-cache/dist/scipy-1.7.3.tar.gz
Running pip install:
"/foo/env/bin/python" "-m" "pip" "install" "--no-deps" "-t" "/home/xx/.buildout/eggs/cp38/tmp2xe7embf" "-v" "/home/xx/.buildout/download-cache/dist/scipy-1.7.3.tar.gz"
path=[]

Using pip 22.0.4 from /foo/env/lib/python3.8/site-packages/pip (python 3.8)
Processing /home/xx/.buildout/download-cache/dist/scipy-1.7.3.tar.gz
  Running command pip subprocess to install build dependencies
  Ignoring numpy: markers 'python_version == "3.7" and platform_machine == "aarch64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.10" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_python_implementation == "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_python_implementation == "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and platform_python_implementation == "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.10" and platform_python_implementation == "PyPy"' don't match your environment
....
```

**Comment by gotcha** [comment] 2022-03-07 14:53
Can you report which version of `pip, `setuptools`, `zc.buildout` are being used ?

A minimal `buildout.cfg` to reproduce would be welcome.

**Comment by delijati** [comment] 2022-03-07 15:01
> Can you report which version of `pip`, `setuptools`, `zc.buildout` are being used ?
> 
> A minimal `buildout.cfg` to reproduce would be welcome.

see above :)  Successfully installed pip-22.0.4 setuptools-60.9.3 zc.buildout-3.0.0rc2

**Comment by gotcha** [comment] 2022-03-07 17:55
Sorry, should have read with more attention.

Thx for the buildout.

**Comment by gotcha** [comment] 2022-03-07 19:22
I was about to ask the same question.

On MacOSX, I could not reproduce easily.

I had to pin version since `scipy == 1.8.0` has been released:
```
❯ cat buildout.cfg 
[buildout]
show-picked-versions = true

parts = py

eggs = scipy 

[py]
recipe = zc.recipe.egg
eggs = ${buildout:eggs}
interpreter = py-foo

[versions]
scipy = 1.7.3
```

Nevertheless, unless I downloaded separately the `tgz`source release to `.../dist`, `buildout`would download the wheel. Both with `zc.buildout` `2.13.4` and `3.0.0rc2`.

**Comment by delijati** [comment] 2022-03-07 21:10
Ahh yes forgot to set the pinning :).

Ok deleting the tgz worked, but now i get:

```
Fetching scipy 1.7.3 from: https://files.pythonhosted.org/packages/f8/3d/26a75c8045181c2fab9c76936ca84318a6674707e33e42c727c1d84f1df4/scipy-1.7.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=95c2d250074cfa76715d58830579c64dff7354484b284c2b8b87e5a38321672c

...

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/foo/env/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2250, in main
    getattr(buildout, command)(args)
  File "/foo/env/lib/python3.8/site-packages/zc/buildout/buildout.py", line 855, in install
    installed_files = self[part]._call(recipe.install)
  File "/foo/env/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1651, in _call
    return f()
  File "/home/delicj/.buildout/eggs/cp38/zc.recipe.egg-2.0.7-py3.8-linux-x86_64.egg/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/home/delicj/.buildout/eggs/cp38/zc.recipe.egg-2.0.7-py3.8-linux-x86_64.egg/zc/recipe/egg/egg.py", line 78, in working_set
    ws = self._working_set(
  File "/home/delicj/.buildout/eggs/cp38/zc.recipe.egg-2.0.7-py3.8-linux-x86_64.egg/zc/recipe/egg/egg.py", line 161, in _working_set
    ws = zc.buildout.easy_install.install(
  File "/foo/env/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 971, in install
    return installer.install(specs, working_set)
  File "/foo/env/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 696, in install
    for dist in self._get_dist(requirement, ws):
  File "/foo/env/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 581, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/foo/env/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1913, in _move_to_eggs_dir_and_compile
    unpacker(dist.location, tmp_dest)
  File "/foo/env/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1847, in unpack_wheel
    wheel.install_as_egg(os.path.join(dest, wheel.egg_name()))
  File "/foo/env/lib/python3.8/site-packages/setuptools/wheel.py", line 95, in install_as_egg
    self._install_as_egg(destination_eggdir, zf)
  File "/foo/env/lib/python3.8/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
    self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
  File "/foo/env/lib/python3.8/site-packages/setuptools/wheel.py", line 164, in _convert_metadata
    setup_dist.get_command_obj('egg_info'),
  File "/foo/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 859, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/foo/env/lib/python3.8/site-packages/setuptools/__init__.py", line 174, in __init__
    super().__init__(dist)
  File "/foo/env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
env/bin/buildout -nvvv  6,66s user 0,42s system 36% cpu 19,301 total
```

**Comment by gotcha** [comment] 2022-03-07 22:00
This is a bug that happens with `setuptools >= 60`.

You have currently two solutions:
- downgrade `setuptools` with `install "setuptools<60"`
- run `buildout` with the proper environment variable set `SETUPTOOLS_USE_DISTUTILS=stdlib bin/buildout`

I will need to find out how to work around `distutils` support in recent `setuptools`.
As you might know, `distutils` is being deprecated. In this context, `distutils` is now distributed in `setuptools >= 60`. I still do not understand what does not work in `_distutils_hack` which should ensure a peaceful  coexistence of the two `distutils`.

Setting `SETUPTOOLS_USE_DISTUTILS=stdlib` ensures that standard lib `distutils` is used, which `zc.buildout` still needs.

BTW, @delijati, would you happen to know how the source `tgz` landed on your machine ? I have a hard time understanding how.

**Comment by delijati** [comment] 2022-03-09 13:36
> run buildout with the proper environment variable set SETUPTOOLS_USE_DISTUTILS=stdlib bin/buildout
Can confirm this works.

**Comment by icemac** [comment] 2022-03-10 08:29
@delijati Is there something still open or can this issue now get closed?

**Closed** 2022-04-04 09:49 UTC

**Comment by gotcha** [comment] 2022-04-07 19:16
@delijati Would you try https://pypi.org/project/zc.buildout/3.0.0rc3/ ? It should avoid the need for 
`SETUPTOOLS_USE_DISTUTILS=stdlib`.

**Comment by delijati** [comment] 2022-04-08 17:15
@gotcha yes not it works without `SETUPTOOLS_USE_DISTUTILS=stdlib` :+1:
